export const gameSuggestions = [
	{ name: "The Legend of Zelda: Breath of the Wild", platform: "Nintendo Switch", status: 1 },
	{ name: "Super Mario Odyssey", platform: "Nintendo Switch", status: 4 },
	{ name: "God of War", platform: "PlayStation 4", status: 2 },
	{ name: "Red Dead Redemption 2", platform: "PlayStation 4, Xbox One, PC", status: 8 },
	{ name: "The Witcher 3: Wild Hunt", platform: "PlayStation 4, Xbox One, Nintendo Switch, PC", status: 16 },
	{ name: "Dark Souls III", platform: "PlayStation 4, Xbox One, PC", status: 4 },
	{ name: "Hollow Knight", platform: "Nintendo Switch, PlayStation 4, Xbox One, PC", status: 1 },
	{ name: "Celeste", platform: "Nintendo Switch, PlayStation 4, Xbox One, PC", status: 8 },
	{ name: "Final Fantasy VII Remake", platform: "PlayStation 4, PlayStation 5", status: 2 },
	{ name: "Animal Crossing: New Horizons", platform: "Nintendo Switch", status: 4 },
	{ name: "Fortnite", platform: "PlayStation, Xbox, Nintendo Switch, PC, Mobile", status: 16 },
	{ name: "Apex Legends", platform: "PlayStation 4, Xbox One, Nintendo Switch, PC", status: 8 },
	{ name: "Among Us", platform: "PC, Mobile, Nintendo Switch", status: 1 },
	{ name: "Cyberpunk 2077", platform: "PlayStation 4, Xbox One, PC", status: 2 },
	{ name: "Ghost of Tsushima", platform: "PlayStation 4, PlayStation 5", status: 4 },
	{ name: "Doom Eternal", platform: "PlayStation 4, Xbox One, Nintendo Switch, PC", status: 8 },
	{ name: "Persona 5 Royal", platform: "PlayStation 4, PlayStation 5", status: 16 },
	{ name: "Resident Evil Village", platform: "PlayStation, Xbox, PC", status: 1 },
	{ name: "Sekiro: Shadows Die Twice", platform: "PlayStation 4, Xbox One, PC", status: 2 },
	{ name: "Monster Hunter: World", platform: "PlayStation 4, Xbox One, PC", status: 4 },
	{ name: "Minecraft", platform: "PlayStation, Xbox, Nintendo Switch, PC, Mobile", status: 16 },
	{ name: "Assassin's Creed Valhalla", platform: "PlayStation, Xbox, PC", status: 8 },
	{ name: "Halo Infinite", platform: "Xbox One, Xbox Series X|S, PC", status: 2 },
	{ name: "Overwatch", platform: "PlayStation, Xbox, Nintendo Switch, PC", status: 1 },
	{ name: "League of Legends", platform: "PC", status: 4 },
	{ name: "Grand Theft Auto V", platform: "PlayStation, Xbox, PC", status: 8 },
	{ name: "Call of Duty: Warzone", platform: "PlayStation, Xbox, PC", status: 16 },
	{ name: "Destiny 2", platform: "PlayStation, Xbox, PC", status: 2 },
	{ name: "Bloodborne", platform: "PlayStation 4", status: 4 },
	{ name: "Stardew Valley", platform: "PlayStation, Xbox, Nintendo Switch, PC, Mobile", status: 8 }
];
